### ISSUE TITLE
Authentication enabled

### ISSUE THREAD

**Issue by websecusa** [michaelhidalgo/attack-to-elk#1]
Is it possible to leverage your tool with an elasticsearch that enables authentication?

**Comment by michaelhidalgo** [comment]
Hey @websecusa, I apologize for the delay. Can you please elaborate a bit more on what is your use case?

Thansk

**Comment by michaelhidalgo** [comment]
I think that's a simple change, for example in here https://github.com/michaelhidalgo/attack-to-elk/blob/master/Elastic_Search.py#L13, I could allow basic auth.
`from elasticsearch import Elasticsearch

# you can use RFC-1738 to specify the url
es = Elasticsearch(['https://user:secret@localhost:443'])

# ... or specify common parameters as kwargs

es = Elasticsearch(
    ['localhost', 'otherhost'],
    http_auth=('user', 'secret'),
    scheme="https",
    port=443,
)`

**Comment by Le-non** [comment]
Hi,
I used RFC-1738 to specify the Elasticsearch URL with authentication. However, when I launch attack-to-elk.py I get this stack trace:
```Parsing and indexing MITRE ATT&CK
HEAD https://127.0.0.1:9200/mitre-attack-tactics [status:N/A request:0.038s]
Traceback (most recent call last):
  File "/home/lenon/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/lenon/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/lenon/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/lenon/.local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/lenon/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 357, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

During handling of the above exception, another exception occurred:
[...]
```

Do you get the same behavior on your end?

**Comment by michaelhidalgo** [comment]
Hey @websecusa:

I installed  ELK 7 with XPAC enable, the code in the Elasticsearch class was changed for this one :

You can change the basic HTTP Authentication header with your settings. Also, since I'm running it locally the schema is http.


```
 self.es = Elasticsearch(
                                    es_host,
                                    http_auth   = ('elastic', 'anypassword'),
                                    scheme      = "http",
                                    port        = es_port,
                                )
        self.index  = index
```
I hope it helps.

**Comment by websecusa** [comment]
Awesome!  Thanks so much for your contributions to the community!!!

**Comment by michaelhidalgo** [comment]
Thanks @websecusa , feel free to open up any other issue you might find
