### ISSUE TITLE
index pattern's purpose

### ISSUE THREAD

**Issue by omrirefaeli** [michaelhidalgo/attack-to-elk#2]
Hey,
what data is supposed to be fed into the index patterns you created?
what is their purpose?
Thank you

**Comment by michaelhidalgo** [comment]
Hey @omrirefaeli , sorry for the late response.
Please check out this blog post that explains on detail why those index patterns have been create https://michaelhidalgocr.blogspot.com/2019/01/mitre-att-as-kibana-dashboard-part-ll.html
