### ISSUE TITLE
File "attack-to-elk.py", line 13, in <module>

### ISSUE THREAD

**Issue by Mangolinux** [michaelhidalgo/attack-to-elk#3]
Getting Error ModuleNotFoundError: No module named 'elasticsearch
![Elk-MAScreenshot from 2020-04-28 18-24-40](https://user-images.githubusercontent.com/15704533/80543774-a592cc80-897d-11ea-8337-65a8bd088dd9.png)

**Comment by michaelhidalgo** [comment]
Hi @Mangolinux , did you try to create the virtual environment? What operating system is that one so I can try to reproduce the issue?

**Comment by Mangolinux** [comment]
The OS is Pop-OS 20.4 (Ubuntu)

**Comment by Mangolinux** [comment]
This is still an issue, where do I get the ModuleNotFoundError: No module named 'elasticsearch'

**Comment by Mangolinux** [comment]
I got the elasticsearch module installed via pip3 install elasticsearch

**Comment by Mangolinux** [comment]
Now I am getting this error elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, '')
 How do I pass my Elastic credentials with your script?

**Comment by Mangolinux** [comment]
I figured out, the solution was in the closed issues https://github.com/michaelhidalgo/attack-to-elk/issues/1

**Comment by michaelhidalgo** [comment]
thanks @Mangolinux , closing this out.
